# -*- coding: utf-8 -*-
"""summarizer_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13LsrKc9WmeEsNwbG8_pr32EdC1PhPDW6
"""

INPUT_TEXT = open("IT_ACT_2000_SAMPLE_INPUT.txt",encoding='utf-8')

IT_SECTION = INPUT_TEXT.read()  # reads N bytes in the from of string

type(IT_SECTION) # checking the type i.e string type

IT_SECTION  # variable give output of the text taken from IT_ACT_2000_SAMPLE_INPUT.txt

text = IT_SECTION

import re

# Preprocessing the data
text = re.sub(r'\[[0-9]*\]',' ',text)
text = re.sub(r'\s+',' ',text)

clean_text = text.lower()
clean_text = re.sub(r'\W',' ',clean_text)
clean_text = re.sub(r'\d',' ',clean_text)
clean_text = re.sub(r'\s+',' ',clean_text)

clean_text

import nltk
nltk.download('stopwords')
nltk.download('punkt')

# Tokenize sentences
sentences = nltk.sent_tokenize(text)

sentences

# Stopword list
stop_words = nltk.corpus.stopwords.words('english')

# Word counts 
word2count = {}
for word in nltk.word_tokenize(clean_text):
    if word not in stop_words:
        if word not in word2count.keys():
            word2count[word] = 1
        else:
            word2count[word] += 1

print(word2count)

# Converting counts to weights
max_count = max(word2count.values())
for key in word2count.keys():
    word2count[key] = word2count[key]/max_count

print(word2count)

# Product sentence scores    
sent2score = {}
for sentence in sentences:
    for word in nltk.word_tokenize(sentence.lower()):
        if word in word2count.keys():
            if len(sentence.split(' ')) < 25:
                if sentence not in sent2score.keys():
                    sent2score[sentence] = word2count[word]
                else:
                    sent2score[sentence] += word2count[word]

print(sent2score)

import heapq
# Gettings best 5 lines             
best_sentences = heapq.nlargest(5, sent2score, key=sent2score.get)

print('---------------------------------------------------------')
for sentence in best_sentences:
    print(sentence)